#!/bin/bash
#
# sbupdate -- Generate and sign kernel images for UEFI Secure Boot on Arch Linux
# Copyright (C) 2016 Andrey Vihrov <andrey.vihrov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

readonly CONFFILE="/etc/default/sbupdate"

# Print an error and return unsuccessfully
#  $1: error message
function error() {
  echo "$0: error: $1" >&2
  return 1
}

# Load configuration
function load_config() {
  KEY_DIR="/root/secure-boot"
  KEYFILE="DB.key"
  CRTFILE="DB.crt"
  ESP_DIR="/boot"
  OUT_DIR="EFI/Arch"
  SPLASH="/usr/share/systemd/bootctl/splash-arch.bmp"
  BACKUP=1
  EXTRA_SIGN=()
  declare -g -A CMDLINE INITRD
  # shellcheck disable=SC1090
  source "${CONFFILE}"

  [[ -d "${ESP_DIR}" ]] || error "${ESP_DIR} does not exist"
  [[ -n "${CMDLINE_DEFAULT:+x}" ]] \
    || error "CMDLINE_DEFAULT is not defined or empty in ${CONFFILE}"

  readonly KEY_DIR KEYFILE CRTFILE ESP_DIR OUT_DIR SPLASH BACKUP EXTRA_SIGN CMDLINE_DEFAULT
  readonly -A CMDLINE INITRD
}

# Parse script arguments
#  $@: arguments
function parse_args() {
  HOOK=0

  for arg in "$@"; do
    if [[ "${arg}" == "--hook" ]]; then
      HOOK=1
    else
      error "unknown argument: ${arg}"
    fi
  done

  readonly HOOK
}

# Find the location of the systemd EFI stub
function find_efi_stub() {
  local uname; uname="$(uname -m)"
  case "${uname}" in
    x86_64)
      readonly EFISTUB="/usr/lib/systemd/boot/efi/linuxx64.efi.stub"
      ;;
    i686)
      readonly EFISTUB="/usr/lib/systemd/boot/efi/linuxia32.efi.stub"
      ;;
    *)
      error "unsupported architecture: ${uname}"
      ;;
  esac
}

# Check if we need to prepend anything to the initramfs file
function setup_initrd_prepend() {
  INITRD_PREPEND=()
  [[ -f "/boot/intel-ucode.img" ]] && INITRD_PREPEND+=('/boot/intel-ucode.img')
  [[ -f "/boot/amd-ucode.img" ]] && INITRD_PREPEND+=('/boot/amd-ucode.img')
  readonly -a INITRD_PREPEND
}

# Create a list of kernels to process
function get_kernels() {
  local all_kernels=(/boot/vmlinuz-*); all_kernels=("${all_kernels[@]#/boot/vmlinuz-}")
  local force_all=0
  declare -g -a KERNELS OLD_KERNELS

  if (( HOOK )); then
    # The script was run from the hook. Read standard input to determine
    # which kernels we need to update.
    while read -r target; do
      if [[ "${target}" =~ ^boot/vmlinuz-(.+)$ ]]; then
        # Regular kernel
        if [[ ! -f "/${target}" ]]; then
          # We are removing this kernel
          OLD_KERNELS+=("${BASH_REMATCH[1]}")
        else
          KERNELS+=("${BASH_REMATCH[1]}")
        fi
      else
        # Another dependency; update all kernels
        force_all=1
      fi
    done
  else
    # The script was run by the user
    force_all=1
  fi

  if (( force_all )); then
    KERNELS=("${all_kernels[@]}")
  fi
  readonly -a KERNELS OLD_KERNELS
}

# Create temporary files for update_kernel()
function create_tmpfiles() {
  INITRD_TMP="$(mktemp)"
  CMDLINE_TMP="$(mktemp)" || { rm -f "${INITRD_TMP}"; return 1; }
  trap 'rm -f "${INITRD_TMP}" "${CMDLINE_TMP}"' EXIT
  readonly INITRD_TMP CMDLINE_TMP
}

# Return output file path corresponding to a kernel
#   $1: kernel name
#   $2: initrd file name
function output_name() {
  [[ "$2" =~ /boot/initramfs-$1([a-z-]*).img ]] || \
    error "invalid initramfs '$2' for kernel $1"
  echo "${ESP_DIR}/${OUT_DIR}/$1${BASH_REMATCH[1]}-signed.efi"
}

# Remove signed images corresponding to a kernel
#   $1: kernel name
function remove_kernel() {
  local initrds="${INITRD[$1]:-/boot/initramfs-$1.img}"
  local output
  echo "Removing kernel images for $1..."
  for initrd in ${initrds}; do
    output="$(output_name "$1" "${initrd}")"
    rm -f "${output}" "${output}.bak"
  done
}

# Generate a signed kernel image for the kernel and initramfs
#   $1: kernel name
#   $2: initrd file path
#   #3: output name
function update_kernel_with_initrd() {
  local image="/boot/vmlinuz-$1"
  local cmdline="${CMDLINE[$1]:-${CMDLINE_DEFAULT}}"
  local output="${3}"

  echo "Generating and signing $(basename "${output}")"

  # Back up existing file if present
  if (( BACKUP )) && [[ -f "${output}" ]]; then
    mv "${output}" "${output}.bak"
  fi
  
  # Create cmdline file
  echo -n "${cmdline}" > "${CMDLINE_TMP}"

  # Join all initramfs files. Refer to:
  #   https://www.kernel.org/doc/Documentation/early-userspace/buffer-format.txt
  #   https://www.kernel.org/doc/Documentation/x86/early-microcode.txt
  cat "${INITRD_PREPEND[@]}" "${2}" > "${INITRD_TMP}"

  # Create a combined binary with systemd EFI stub. For additional information see:
  #   https://github.com/systemd/systemd/blob/master/src/boot/efi/stub.c
  #   https://github.com/systemd/systemd/blob/master/test/test-efi-create-disk.sh
  objcopy \
    --add-section .osrel="/etc/os-release"  --change-section-vma .osrel=0x20000    \
    --add-section .cmdline="${CMDLINE_TMP}" --change-section-vma .cmdline=0x30000  \
    --add-section .splash="${SPLASH}"       --change-section-vma .splash=0x40000   \
    --add-section .linux="${image}"         --change-section-vma .linux=0x2000000  \
    --add-section .initrd="${INITRD_TMP}"   --change-section-vma .initrd=0x3000000 \
    "${EFISTUB}" "${output}"

  # Sign the resulting output file
  sbsign --key "${KEY_DIR}/${KEYFILE}" --cert "${KEY_DIR}/${CRTFILE}" --output "${output}" "${output}"
}

# Generate a signed kernel image for each initrd
#   $1: kernel name
function update_kernel() {
  local initrds="${INITRD[$1]:-/boot/initramfs-$1.img}"
  local output
  for initrd in ${initrds}; do
    output="$(output_name "$1" "${initrd}")"
    update_kernel_with_initrd "$1" "${initrd}" "${output}"
  done
}

# Sign a user-specified extra file
#   $1: file path
function sign_extra_file() {
  if sbverify --cert "${KEY_DIR}/${CRTFILE}" "$1" >/dev/null 2>&1; then
    echo "Skipping already signed file $1"
  else
    echo "Signing $1..."
    sbsign --key "${KEY_DIR}/${KEYFILE}" --cert "${KEY_DIR}/${CRTFILE}" --output "$1" "$1"
  fi
}

# Entry point
function main() {
  load_config
  parse_args "$@"

  find_efi_stub
  setup_initrd_prepend
  get_kernels

  create_tmpfiles

  mkdir -p "${ESP_DIR}/${OUT_DIR}"
  for k in "${OLD_KERNELS[@]}"; do
    remove_kernel "$k"
  done
  for k in "${KERNELS[@]}"; do
    update_kernel "$k"
  done

  if (( ! HOOK )); then
    for f in "${EXTRA_SIGN[@]}"; do
      sign_extra_file "$f"
    done
  fi
}

main "$@"

# vim:set ts=2 sw=2 et:
